### ISSUE TITLE
criterion of specific moible phone choosing?

### ISSUE THREAD

**Issue by kaiq663** [dhryougit/AFM#1]
When your paper will be released? Looking forward to~

**Comment by dhryougit** [comment]
The paper will be released together when the CVPR papers are released!

**Comment by kaiq663** [comment]
> The paper will be released together when the CVPR papers are released!

Thanks, there exist XIAOMI8,IPHONE_6S,IPHONE13,IPHONE5S,OPPO_R11S,HUAWEI_honor6X,HUAWEI_Mate40Pro in real world mobile phone datasets of Denoising-Comparison paper.Here are my questions.

question1: why do you choose IPHONE13 instead of 6S or 5S? why do you choose HUAWEI_honor6X instead of Mate40Pro?

question2:Is there a criterion of choosing a specific mobile phone dataset for OOD comparsion?

**Comment by dhryougit** [comment]
Among mobile phones, we chose one each from the widely used brands, Huawei and iPhone. Within each brand, the noise distribution in the datasets does not significantly differ across models, so we selected one from each brand without any special criteria for evaluation. Thank you!
